function df = df(x,y,z)
%DF
%    DF = DF(X,Y,Z)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    2025-07-09 12:47:37

t2 = cos(x);
t3 = sin(x);
df = [x.*2.0-t3.*y.^2+t2.*z.^2;t2.*y.*2.0;t3.*z.*2.0];
end
