function d_f = div_f(x,y,z)
%DIV_F
%    D_F = DIV_F(X,Y,Z)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    2025-07-09 12:49:02

t2 = cos(x);
t3 = sin(x);
d_f = t2.*2.0+t3.*2.0-t2.*y.^2-t3.*z.^2+2.0;
end
