function g_f = grad_f(x,y,z)
%GRAD_F
%    G_F = GRAD_F(X,Y,Z)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    2025-07-09 12:49:02

t2 = cos(x);
t3 = sin(x);
g_f = [x.*2.0-t3.*y.^2+t2.*z.^2;t2.*y.*2.0;t3.*z.*2.0];
end
