baseURL = 'https://www.windtunnel.cn/'
languageCode = 'en-us'
defaultContentLanguage = 'zh'
hasCJKLanguage = true
title = '技术写作练习：写得越多，写得越开心'
email = 'qchen2015@hotmail.com'
github_username =  'qchen-fdii-cardc'
author = 'Qin Chen, Ph.D. qchen2015@hotmail.com'
theme = "nostyleplease"
staticDir = ["static"]

[params]
  mathkatex = false

[taxonomies]
  category = "categories"
  tag = "tags"


[markup]
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ''
    hl_inline = false
    lineAnchors = ''
    lineNoStart = 1
    lineNos = true
    lineNumbersInTable = false
    noClasses = true
    style = 'monokai'
    tabWidth = 4
    wrapperClass = 'highlight'

  [markup.tableOfContents]
    endLevel = 2
    startLevel = 2
    ordered = true
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.passthrough]
        enable = true
        [markup.goldmark.extensions.passthrough.delimiters]
          block = [['\[', '\]'], ['$$', '$$']]
          inline = [['\(', '\)'], ['$', '$']]