baseURL = 'https://qchen-fdii-cardc.github.io/'
languageCode = 'en-us'
defaultContentLanguage = 'zh'
hasCJKLanguage = true
title = '技术写作练习：写得越多，写得越开心'
author = 'Qin Chen, Ph.D. qchen2015@hotmail.com'
theme = "nostyleplease"


[params]
  toc = true
  tocBorder = true
  show_reading_time = true