baseURL = 'https://example.com/'
languageCode = 'en-us'
defaultContentLanguage = 'zh'
hasCJKLanguage = true
title = '我的网站'
email = 'qchen2015@hotmail.com'
github_username =  'qchen-fdii-cardc'
author = 'Qin Chen, Ph.D. qchen2015@hotmail.com'
theme = "nostyleplease"
staticDir = ["static"]



[taxonomies]
  category = "categories"
  tag = "tags"


[markup]
  [markup.tableOfContents]
    endLevel = 2
    startLevel = 2
    ordered = true
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.passthrough]
        enable = true
        [markup.goldmark.extensions.passthrough.delimiters]
          block = [['\[', '\]'], ['$$', '$$']]
          inline = [['\(', '\)'], ['$', '$']]