AppFile = "updateDropDown.m";
opts = compiler.build.StandaloneApplicationOptions(AppFile, ...
    AdditionalFiles=["..\matlab-img\icon.jpg"], ...
    ExecutableIcon="..\matlab-img\icon.jpg", ...
    ExecutableName="DropDownExample", ...
    OutputDir=".", ...
    ExecutableVersion="1.0", ...
    Verbose='on');

compiler.build.standaloneApplication(opts)